wandb_version: 1

epochs:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 12
lr:
  desc: null
  value: 0.0006
loss_fn:
  desc: null
  value: crossentropyloss
_wandb:
  desc: null
  value:
    python_version: 3.11.3
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.30.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691818189.085352
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      3:
      - 16
      - 23
      4: 3.11.3
      5: 0.15.4
      6: 4.30.1
      8:
      - 5
